// <auto-generated />
using System;
using InternProject1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternProject1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122024651_employee")]
    partial class employee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternProject1.Models.Attendance", b =>
                {
                    b.Property<int>("Attendance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Attendance_ID"));

                    b.Property<DateTime?>("BreakStartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ClockInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ClockOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<bool>("HasTakenBreak")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnBreak")
                        .HasColumnType("bit");

                    b.Property<string>("Location_Lat_Long")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan?>("TotalBreakTime")
                        .HasColumnType("time");

                    b.HasKey("Attendance_ID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("InternProject1.Models.Department", b =>
                {
                    b.Property<int>("Department_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Department_ID"));

                    b.Property<string>("Department_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Manager_ID")
                        .HasColumnType("int");

                    b.HasKey("Department_ID");

                    b.HasIndex("Manager_ID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("InternProject1.Models.Employee", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee_ID"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Department_ID")
                        .HasColumnType("int");

                    b.Property<string>("Employee_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QR_Code_Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shift_ID")
                        .HasColumnType("int");

                    b.HasKey("Employee_ID");

                    b.HasIndex("Department_ID");

                    b.HasIndex("Shift_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InternProject1.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Leave_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Leave_ID"));

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Leave_Balance")
                        .HasColumnType("int");

                    b.Property<string>("Leave_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Request_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Leave_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("InternProject1.Models.Manager", b =>
                {
                    b.Property<int>("Manager_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manager_ID"));

                    b.Property<string>("Manager_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Manager_ID");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("InternProject1.Models.Report", b =>
                {
                    b.Property<int>("Report_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Report_ID"));

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Generated_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAbsend")
                        .HasColumnType("int");

                    b.Property<int>("TotalPresent")
                        .HasColumnType("int");

                    b.HasKey("Report_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("InternProject1.Models.Shift", b =>
                {
                    b.Property<int>("Shift_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Shift_ID"));

                    b.Property<TimeSpan>("End_Time")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Start_Time")
                        .HasColumnType("time");

                    b.HasKey("Shift_ID");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("InternProject1.Models.Department", b =>
                {
                    b.HasOne("InternProject1.Models.Manager", "Manager")
                        .WithMany("Departments")
                        .HasForeignKey("Manager_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("InternProject1.Models.Employee", b =>
                {
                    b.HasOne("InternProject1.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Department_ID");

                    b.HasOne("InternProject1.Models.Shift", "Shift")
                        .WithMany("Employees")
                        .HasForeignKey("Shift_ID");

                    b.Navigation("Department");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("InternProject1.Models.LeaveRequest", b =>
                {
                    b.HasOne("InternProject1.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("InternProject1.Models.Report", b =>
                {
                    b.HasOne("InternProject1.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("InternProject1.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("InternProject1.Models.Manager", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("InternProject1.Models.Shift", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
